# This is a basic workflow to help you get started with Actions

name: CI
on: 

  push: 

    branches: [ develop ] 

    paths: 

    - 'calculadora.py' 

    - 'lint.py' 
 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@v2 

    - name: Set up Python 3.8 

      uses: actions/setup-python@v2 

      with: 

        python-version: 3.8 

    - name: Install dependencies 

      run: | 

        python -m pip install --upgrade pip 

        pip install pylint
        
    - name:  Unittest

      run: | 

        python test_module.py 

    - name: Lint with pylint 

      run: | 

        python lint.py 
