
# This is a basic workflow to help you get started with Actions
name: CI
on: [push, pull_request]
jobs: 
  Estabilizacao: 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "Unittests"
      - run: python test_module.py
      - run: echo "Lint"
      - run: python lint.py